# Makefile to build the AmigaOS4 SDL tests

CC     = m68k-apple-macos-gcc
CXX     = m68k-apple-macos-g++
#CRT   ?= newlib
#CFLAGS = -mcrt=$(CRT) -gstabs -O3 -Wall -I../include -I../include/build_config -I../src -DHAVE_OPENGL
CFLAGS = -Wall -I../include -I../include/build_config -I../src
LIBS   = -L.. -lSDL3_test -lSDL3  -lOpenGLLibrary -lm -Wl,--relax -Wl,-Map,output.map -Wl,--gc-sections


CFLAGS+= -D__MACOSCLASSIC__ -DSDL_MACOSCLASSIC_INPUTSPROCKET=1 -DSDL_MACOSCLASSIC_TINYGL=1 -DHAVE_OPENGL=1


SRC_FILES = $(wildcard *.c)
DEPS = $(SRC_FILES:.c=.d)


TARGETS = \
	checkkeys \
	childprocess \
	helloworld \
	loopwave \
	sdl3benchmark \
	testasyncio \
	testatomic \
	testaudio \
	testaudiohotplug \
	testaudioinfo \
	testaudiorecording \
	testaudiostreamdynamic \
	testautomation \
	testbounds \
	testclipboard \
	testcolorspace \
	testcontroller \
	testcustomcursor \
	testdialog \
	testdisplayinfo \
	testdraw \
	testdrawchessboard \
	testdropfile \
	testerror \
	testfile \
	testfilesystem \
	testgeometry \
	testgl \
	testgles \
	testgles2 \
	testhaptic \
	testhittesting \
	testhotplug \
	testiconv \
	testime \
	testintersections \
	testkeys \
	testloadso \
	testlocale \
	testlock \
	testmessage \
	testmouse \
	testmultiaudio \
	testoffscreen \
	testoverlay \
	testpen \
	testplatform \
	testpower \
	testprocess \
	testqsort \
	testrelative \
	testrendercopyex \
	testrendertarget \
	testresample \
	testrumble \
	testrwlock \
	testscale \
	testsem \
	testsensor \
	testshader \
	testshape \
	testsprite \
	testspriteminimal \
	testspritesurface \
	teststreaming \
	testsurround \
	testthread \
	testtime \
	testtimer \
	testurl \
	testver \
	testviewport \
	testvulkan \
	testwm \
	testyuv \
	torturethread \

all: $(TARGETS)

checkkeys: checkkeys.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

childprocess: childprocess.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

helloworld: helloworld.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

loopwave: loopwave.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

sdl3benchmark: sdl3benchmark.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testasyncio: testasyncio.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testatomic: testatomic.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testaudio: testaudio.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testaudiohotplug: testaudiohotplug.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testaudioinfo: testaudioinfo.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testaudiorecording: testaudiorecording.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testaudiostreamdynamic: testaudiostreamdynamic.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testautomation: testautomation.o \
		      testautomation_audio.o \
		      testautomation_blit.o \
		      testautomation_clipboard.o \
		      testautomation_events.o \
		      testautomation_guid.o \
		      testautomation_hints.o \
		      testautomation_images.o \
		      testautomation_intrinsics.o \
		      testautomation_iostream.o \
		      testautomation_joystick.o \
		      testautomation_keyboard.o \
		      testautomation_log.o \
		      testautomation_main.o \
		      testautomation_math.o \
		      testautomation_mouse.o \
		      testautomation_pixels.o \
		      testautomation_platform.o \
		      testautomation_properties.o \
		      testautomation_rect.o \
		      testautomation_render.o \
		      testautomation_sdltest.o \
		      testautomation_stdlib.o \
		      testautomation_subsystems.o \
		      testautomation_surface.o \
		      testautomation_time.o \
		      testautomation_timer.o \
		      testautomation_video.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testbounds: testbounds.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testclipboard: testclipboard.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testcolorspace: testcolorspace.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testcontroller: testcontroller.o gamepadutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testcustomcursor: testcustomcursor.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testdialog: testdialog.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testdisplayinfo: testdisplayinfo.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testdraw: testdraw.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testdrawchessboard: testdrawchessboard.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testdropfile: testdropfile.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testerror: testerror.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testfile: testfile.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testfilesystem: testfilesystem.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testgeometry: testgeometry.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testgl: testgl.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testgles: testgles.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testgles2: testgles2.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testhaptic: testhaptic.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testhittesting: testhittesting.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testhotplug: testhotplug.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testiconv: testiconv.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testime: testime.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testintersections: testintersections.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testkeys: testkeys.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testloadso: testloadso.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testlocale: testlocale.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testlock: testlock.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testmessage: testmessage.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testmouse: testmouse.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testmultiaudio: testmultiaudio.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

#testnative: testnative.o testnativeapple-macos4.o testutils.o
#	$(CXX) -o $@.code.bin $^ $(LIBS)
#	../../bin2app.sh $@

testoffscreen: testoffscreen.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testoverlay: testoverlay.o testyuv_cvt.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testpen: testpen.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testplatform: testplatform.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testpower: testpower.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testprocess: testprocess.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testqsort: testqsort.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testrelative: testrelative.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testrendercopyex: testrendercopyex.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testrendertarget: testrendertarget.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testresample: testresample.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testrumble: testrumble.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testrwlock: testrwlock.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testscale: testscale.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testsem: testsem.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testsensor: testsensor.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testshader: testshader.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testshape: testshape.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testsprite: testsprite.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testspriteminimal: testspriteminimal.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testspritesurface: testspritesurface.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

teststreaming: teststreaming.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testsurround: testsurround.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testthread: testthread.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testtime: testtime.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testtimer: testtimer.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testurl: testurl.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testver: testver.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testviewport: testviewport.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testvulkan: testvulkan.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testwm: testwm.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

testyuv: testyuv.o testyuv_cvt.o testutils.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

torturethread: torturethread.o
	$(CXX) -o $@.code.bin $^ $(LIBS)
	../../bin2app.sh $@

clean:
	rm -f $(TARGETS) *.o $(DEPS)

%.d : %.c
	@echo Making dependencies for $<
	@$(CC) -MM -MP -MT $(@:.d=.o) -o $@ $< $(CFLAGS)

%.o : %.c
	@echo Compiling $<
	$(CC) -o $@ -c $< $(CFLAGS)

# Load .d files
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPS)
endif
