
all:
	make -C dummy_dir -f Makefile.r68
	make -C macos8addons -f Makefile.r68
	make -C SDL-main -f Makefile.r68
	
clean:
	make -C __debugbreak -f Makefile.r68 clean
	make -C dummy_atomic -f Makefile.r68 clean
	make -C dummy_dir -f Makefile.r68 clean
	make -C dummy_image -f Makefile.r68 clean
	make -C dummy_libstdcpp -f Makefile.r68 clean
	make -C dummy_memory -f Makefile.r68 clean
	make -C dummy_pthreads -f Makefile.r68 clean
	make -C dummy_time -f Makefile.r68 clean
	make -C mytests -f Makefile.r68 clean
	make -C SDL-main -f Makefile.r68 clean
	rm -f */*.o */*.a
