
all:
	make -C dummy_dir -f Makefile.r68
	make -C macos8addons -f Makefile.r68
	make -C SDL-main -f Makefile.r68
	
clean:
	make -C dummy_dir -f Makefile.r68 clean
	make -C macos8addons -f Makefile.r68 clean
	make -C SDL-main -f Makefile.r68 clean
	rm -f */*.o */*.a
